/**
 * Autogenerated by Thrift Compiler (0.10.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package net.thrift.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class testConstants
{

	/**
	 * Thrift也支持定义常量。
	 * 对于结构复杂的常量，支持使用JSON形式来表示。
	 */
	public static final int TEST_CONST_NUMBER = 10;

	public static final java.util.Map<java.lang.String, java.lang.String> TEST_CONST_MAP = new java.util.HashMap<java.lang.String, java.lang.String>();

	static
	{
		TEST_CONST_MAP.put("hello", "world");
	}

}
